import { Montserrat } from 'next/font/google'
import './globals.css'
import Navbar from './component/Navbar'
import Footer from './component/Footer'
import Script from 'next/script'

const montserrat = Montserrat({ 
  subsets: ['latin'], 
  variable: "--font-mont" })

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-mont bg-light dark:bg-dark`}>
        
        <Navbar />
        <main className="flex w-full items-center text-dark dark:text-light min-h-screen">

        {children}
        </main>
        <Footer />
        <Script id="theme-switcher" strategy='beforeInteractivity'>
          {
            `if(localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
              document.documentElement.classList.add('dark')
            } else {
              document.documentElement.classList.remove('dark')
            }
          `}
        </Script>
      </body>
    </html>
  )
}
